// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NI_BE.DataDb;

#nullable disable

namespace NI_BE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231027081019_InitialDatabaseMigration")]
    partial class InitialDatabaseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NI_BE.DataDb.Models.TRANS_MW_ERC_PM_TN_RADIO_LINK_POWER", b =>
                {
                    b.Property<DateTime>("DATETIME_KEY")
                        .HasColumnType("datetime2");

                    b.Property<string>("DIRECTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAILUREDESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FARENDTID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("INTERVAL")
                        .HasColumnType("int");

                    b.Property<string>("LINK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MAXRXLEVEL")
                        .HasColumnType("real");

                    b.Property<float>("MAXTXLEVEL")
                        .HasColumnType("real");

                    b.Property<float>("MINRXLEVEL")
                        .HasColumnType("real");

                    b.Property<float>("MINTXLEVEL")
                        .HasColumnType("real");

                    b.Property<string>("NEALIAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("NEID")
                        .HasColumnType("real");

                    b.Property<int>("NETWORK_SID")
                        .HasColumnType("int");

                    b.Property<string>("NETYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBJECT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PORT")
                        .HasColumnType("int");

                    b.Property<float>("RXLEVELBELOWTS1")
                        .HasColumnType("real");

                    b.Property<float>("RXLEVELBELOWTS2")
                        .HasColumnType("real");

                    b.Property<string>("SLOT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TIME")
                        .HasColumnType("datetime2");

                    b.Property<float>("TXLEVELABOVETS1")
                        .HasColumnType("real");

                    b.ToTable("TRANS_MW_ERC_PM_TN_RADIO_LINK_POWERs");
                });

            modelBuilder.Entity("NI_BE.DataDb.Models.TRANS_MW_ERC_PM_WAN_RFINPUTPOWER", b =>
                {
                    b.Property<DateTime>("DATETIME_KEY")
                        .HasColumnType("datetime2");

                    b.Property<string>("DIRECTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FARENDTID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("INTERVAL")
                        .HasColumnType("int");

                    b.Property<string>("NEALIAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("NEID")
                        .HasColumnType("real");

                    b.Property<int>("NETWORK_SID")
                        .HasColumnType("int");

                    b.Property<string>("NETYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NODENAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBJECT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PORT")
                        .HasColumnType("int");

                    b.Property<float>("RFINPUTPOWER")
                        .HasColumnType("real");

                    b.Property<string>("SLOT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TIME")
                        .HasColumnType("datetime2");

                    b.ToTable("TRANS_MW_ERC_PM_WAN_RFINPUTPOWERs");
                });
#pragma warning restore 612, 618
        }
    }
}
